### ISSUE TITLE
楼主，感谢你的分享，代码写的很好，是我想要的。有个问题，自动测试的时候需要一个iTester.xml的配置文件，是否能分享，以便参考。感谢感谢。

### ISSUE THREAD

**Issue by 656643899** [li-yu/iTester#1]

**Comment by li-yu** [comment]
可以参考我仓库里的 iTesterConfigBuilder

**Comment by 656643899** [comment]
好的，感谢分享。

**Comment by 656643899** [comment]
好的，很好的工具，感谢分享。



zhiguang.zheng@foxmail.com
 
发件人： 呵呵小鱼
发送时间： 2018-12-17 20:57
收件人： li-yu/iTester
抄送： GuangZhi; Author
主题： Re: [li-yu/iTester] 楼主，感谢你的分享，代码写的很好，是我想要的。有个问题，自动测试的时候需要一个iTester.xml的配置文件，是否能分享，以便参考。感谢感谢。 (#1)
可以参考我仓库里的 iTesterConfigBuilder
